CREATE TABLE CLIENT(
ID INTEGER IDENTITY(1,1),
EMAIL VARCHAR(300) NOT NULL,
PASSWORD VARBINARY(50) NOT NULL,
ACESSTOKEN VARCHAR(100) NOT NULL,
DOCUMENT VARCHAR(20) NOT NULL,
NAME VARCHAR(200) NOT NULL,

PHONE VARCHAR(20) NOT NULL,
CONSTRAINT PK_CLIENT PRIMARY KEY (ID)
);
CREATE TABLE CLIENTPLAN(
ID INTEGER IDENTITY(1,1),
CLIENTID INTEGER,
NAME VARCHAR(50) NOT NULL,
MONTHLYVALUE NUMERIC(7,2) NOT NULL,
REQUESTVALUE NUMERIC(6,2) NOT NULL,
CONTRACTEDQUANTITY INTEGER NOT NULL,
EXTRAQUANTITY INTEGER NOT NULL,
CONSTRAINT PK_CLIENT_PLAN PRIMARY KEY (ID),
CONSTRAINT FK_CLIENTPLAN_CLIENT FOREIGN KEY (CLIENTID) REFERENCES CLIENT (ID)
);
CREATE TABLE API(
ID INTEGER IDENTITY(1,1),
NAME VARCHAR(50) NOT NULL,
CONSTRAINT PK_API PRIMARY KEY (ID)
);
CREATE TABLE CLIENTAPI(
CLIENTID INTEGER,
APIID INTEGER,
USERNAME VARCHAR(300) NOT NULL,
PASSWORD VARBINARY(100) NOT NULL,
CONSTRAINT PK_CLIENTAPI PRIMARY KEY (CLIENTID,APIID),
CONSTRAINT FK_CLIENT FOREIGN KEY 
(CLIENTID) REFERENCES CLIENT (ID),
CONSTRAINT FK_API FOREIGN KEY (APIID) REFERENCES API (ID)
);
CREATE TABLE CLIENTCONFIGURATION(
CLIENTID INTEGER,
SMTPHOST VARCHAR(50) NOT NULL,
SMTPUSERNAME VARCHAR(300) NOT NULL,
SMTPPASSWORD VARCHAR(50) NOT NULL,
SMTPPORT INTEGER NOT NULL,
TRACKINGEMAILTEMPLATE VARCHAR(300),
TRACKINGEMAILEVENTTEMPLATE VARCHAR(300),
CONSTRAINT PK_CLIENT_CONFIG PRIMARY KEY (CLIENTID)
);
CREATE TABLE CLIENTAPIREQUEST(
ID INTEGER IDENTITY(1,1),
CLIENTID INTEGER,
PLANID INTEGER,
DT_REQUEST DATE NOT NULL,
URL VARCHAR(300) NOT NULL,
BODY VARCHAR(300) NOT NULL,
RESPONSESTATUS INTEGER NOT NULL,
RESPONSEBODY VARCHAR(300) NOT NULL,
PORTACTIONS VARCHAR(300) NOT NULL,
CONSTRAINT PK_CLIENT_API_RQ PRIMARY KEY (ID),
CONSTRAINT FK_CLIENTID_API_REQUEST FOREIGN KEY (CLIENTID)
REFERENCES CLIENT (ID),
CONSTRAINT FK_PLANID_API_REQUEST FOREIGN KEY (PLANID)
REFERENCES CLIENTPLAN (ID)
);

Create function fun_encriptar(@valor varchar(50))
returns binary(50)
as
begin
declare @encriptado varbinary(50);
set @encriptado=HASHBYTES('SHA1',@valor);
return @encriptado;
end

INSERT INTO CLIENT
(EMAIL,PASSWORD,ACESSTOKEN,DOCUMENT,NAME,PHONE) VALUES
('gustavoysgames@gmail.com',(SELECT dbo.fun_encriptar('outraSenha')),2233,'Meu CPF','Gustavo Yuji Sato','97777-7777');

INSERT INTO CLIENT
(EMAIL,PASSWORD,ACESSTOKEN,DOCUMENT,NAME,PHONE) VALUES
('jao_jao@gmail.com',(SELECT dbo.fun_encriptar('minhaSenha')),1122,'Meu CPF2','Jo�o Man�','98888-8888');

INSERT INTO CLIENT
(CLIENTID,SMTPHOST,SMTPUSERNAME,SMTPPASSWORD,SMTPPORT,TRACKINGEMAILTEMPLATE,TRACKINGEMAILEVENTTEMPLATE) VALUES
(5,'smtp.gmail.com','gysato3@gmail.com','Senha','587','Requisição de nova senha Expresso Api','<p style='color:red'>Foi solicitado uma nova senha para o Expresso Api, sua nova senha é:</p>');

SELECT * FROM CLIENT
UPDATE CLIENTCONFIGURATION SET CLIENTID = 5;
SELECT COUNT(*) FROM Client
DROP TABLE CLIENTCONFIGURATION
DELETE FROM CLIENTCONFIGURATION
select * from INFORMATION_SCHEMA.TABLES